### ISSUE TITLE
3 errors

### ISSUE THREAD

**Issue by android12233** [frinder/frinder-app#175]
2019-05-22 09:52:28.408 27990-27990/com.frinder.frinder E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.frinder.frinder, PID: 27990
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.frinder.frinder.model.User.toString()' on a null object reference
        at com.frinder.frinder.activity.MainActivity.readUserComplete(MainActivity.java:116)
        at com.frinder.frinder.activity.MainActivity$1.onUserReceived(MainActivity.java:61)
        at com.frinder.frinder.dataaccess.UserFirebaseDas$7.onComplete(UserFirebaseDas.java:115)
        at com.google.android.gms.tasks.zzf.run(Unknown Source:23)
        at android.os.Handler.handleCallback(Handler.java:874)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:198)
        at android.app.ActivityThread.main(ActivityThread.java:6729)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
1. error
at com.frinder.frinder.activity.MainActivity.readUserComplete(MainActivity.java:116)
public void readUserComplete(User user) {
        Log.d(TAG, "Read user from firebase " + user.toString());
        //loggedUser has the user fetched from firebase
        loggedUser = user;
    }

2. error
 at com.frinder.frinder.activity.MainActivity$1.onUserReceived(MainActivity.java:61)
 readUserComplete(user);

3. error
at com.frinder.frinder.dataaccess.UserFirebaseDas$7.onComplete(UserFirebaseDas.java:115)
listener.onUserReceived(null);

**Comment by adeseg** [comment]
Any one to help out

**Comment by ArunShewale** [comment]
getting same error. anybody know the solution?
